[workspace]
members = ["calendar-tui"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "GPL-3.0-only"
authors = ["gigas002 <gigas002@pm.me>"]
homepage = "https://github.com/Gigas002/calendar-tui"
description = "Interactive terminal calendar"
repository = "https://github.com/Gigas002/calendar-tui"
version = "0.1.0"
